name: dart_global_toast
description: Global toast to interact between independent app parts

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.1.8
  angular: ^5.3.1
  sass_builder: ^2.1.3
  angular_components: ^0.13.0

dev_dependencies:
  test: ^1.6.0
  pedantic: ^1.9.0
  build_test: ^1.0.0
  angular_test: ^2.3.0
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
